# Generated by Django 4.2.5 on 2023-11-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_updated_at_alter_student_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='seesion_id',
            new_name='session_id',
        ),
    ]
